### PR TITLE
Fix Xamarin.Android Linux generation

### LINKED ISSUE #208: Android projects are generated with Novell targets instead of Xamarin targets on Linux
Android projects generated from Linux are generated with Novell targets file instead of the new Xamarin one. I noticed that you had a check in <a href="https://github.com/Protobuild/Protobuild/blob/35a15c0a1755e15bc4109fffa6c812fd834b7c85/Protobuild.Internal/BuildResources/GenerateProject.CSharp.xslt#L2108">GenerateProject.CSharp.xslt</a> which you could just return true if Protobuild is running on Linux, since Novell targets never existed for it.

### PR DESCRIPTION
**Pull request by cra0zy**
Fixes #208

### CODE REVIEW

**Comment by cra0zy** [comment]
@hach-que Where do I need to sign cla? I know about https://cla.dotnetfoundation.org/ but there is no `Protobuild` under project names.

**Comment by hach-que** [comment]
I'll email folks and see if I can get Protobuild listed there.

**Comment by cra0zy** [comment]
I gotta say you designed the PRs for your repo very poorly with the requirement for having end users regenerate the binary files since any new commit to the main repo will brake all the PRs.

**Comment by hach-que** [comment]
You don't need to compile Protobuild as I will do that anyway before merging any external PRs.

**Comment by hach-que** [comment]
It even says so in the contribution guide: http://protobuild.readthedocs.io/en/latest/contributing.html#we-ll-rebase-your-changes

**Comment by cra0zy** [comment]
README confused me then:
```
If you want to prepare your changes for submission in a PR, run Protobuild.exe --automated-build before you commit in order to run the tests and prepare the final Protobuild executable.
```

**Comment by hach-que** [comment]
Can you sign https://cla2.dotnetfoundation.org/?

**Comment by cra0zy** [comment]
Signed.

**Comment by hach-que** [comment]
Merged as 8689d72.

**Pull request closed without merging**
