### PR TITLE
Add "Exclude" attribute support to Compile tag

### PR DESCRIPTION
**Pull request by ming4883**
According to the following documents:
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-exclude-files-from-the-build
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

The Compile & Content tags did support glob patterns, and "exclude" is an essential complement to "include".
This is very useful for porting existing Unity modules / plugins to Protobuild (for example exclude those files inside the Editor folder while using globs).

### CODE REVIEW

**Comment by hach-que** [comment]
Thanks for this, I'm testing these changes now.

**Comment by ming4883** [comment]
Nice, thank you very much for your fast responds and hopes this feature will soon appear in stable releases.

**Comment by hach-que** [comment]
Just waiting on the tests to pass on the build server, then I'll squash and merge this change in.

**Comment by hach-que** [comment]
Don't worry about that build failure - that's me manually restarting the macOS build.

**Comment by hach-que** [comment]
I'm going to go ahead and merge this, as the macOS agent build is stalling on the new build server and I'm not quite sure of the cause yet (though confident it's not this change).

Thanks for the contribution!

**Pull request merged**
